In [2]:
import pandas as pd
import numpy as np
data=pd.read_csv('bus.csv', encoding='euc-kr',index_col='노선번호')
data=data.fillna('정보없음')
data

,기점,경유지,종점,운영횟수,기점첫차,종점첫차,기점막차,종점막차,유의사항,기준일
노선번호,,,,,,,,,,
1,양평터미널,회현개군천서리보통리대신후포오학,여주터미널,6,06:10,정보없음,20:10,정보없음,정보없음,2020-11-23
1-1,양평터미널,회현개군천서리곡수삼거리옥촌대신오학,여주 곡수 터미널,2,11:40,정보없음,16:10,정보없음,정보없음,2020-11-23
1-10,여주터미널,오학후포대신보통리천서리개군회현,양평터미널,4,07:50,정보없음,21:30,정보없음,정보없음,2020-11-23
1-11,여주 곡수 터미널,오학대신곡수삼거리송촌리천서리회현리양평시장,양평터미널,2,11:30,정보없음,19:10,정보없음,정보없음,2020-11-23
1-12,여주 이포 터미널,오학대신천서리이포개군회현,양평터미널,1,09:30,정보없음,정보없음,정보없음,정보없음,2020-11-23
...,...,...,...,...,...,...,...,...,...,...
9-3,문호리 종점,마진배도장2리정배리서후리수능리소나기마을마진배,정배리 종점,1,17:40,17:55,정보없음,정보없음,정보없음,2020-11-23
9-30 벽,문호리 종점,마진배도장2리정배리서후리수능리소나기마을마진배,정배리 종점,3,08:35,08:50,14:40,14:55,정보없음,2020-11-23
9-6,명달리 종점,노문리수입리서종면사무소문호리양수리국수리아신리오빈리,양평터미널,1,06:35,정보없음,정보없음,정보없음,정보없음,2020-11-23
9-7,문호리 종점,괘미양수리신원리국수역정자리고현리아신리오빈리,양평터미널 고현,1,19:45,정보없음,정보없음,정보없음,정보없음,2020-11-23
9-8,중미산 양현마을,양현마을정배초교정배1리마을회관도장리마진배,문호리 종점,1,07:30,정보없음,정보없음,정보없음,정보없음,2020-11-23

In [3]:
#data.loc['버스번호']
x=data.loc['9-6'] #시리즈 형태
print('기점: ',x['기점'])
print('종점: ',x['종점'])
print('경유지: ',x['경유지'])
print('첫차시간: ',x['기점첫차'])
print('막차시간: ',x['기점막차'])

기점:  명달리 종점
종점:  양평터미널
경유지:  노문리수입리서종면사무소문호리양수리국수리아신리오빈리
첫차시간:  06:35
막차시간:  정보없음

In [13]:
import pandas as pd
import numpy as np

data=pd.read_excel('bus_seoul.xlsx',engine='openpyxl')
data

,노선ID,노선명,순번,NODE_ID,ARS-ID,정류소명,X좌표,Y좌표
0,100100124,0017,1,102000271,3689,청암자이아파트,126.946517,37.534363
1,100100124,0017,2,102000204,3298,청암동강변삼성아파트,126.949304,37.533961
2,100100124,0017,3,102000227,3321,청심경로당,126.950449,37.533744
3,100100124,0017,4,102000210,3304,원효2동주민센터,126.950904,37.534278
4,100100124,0017,5,102000212,3306,산천동,126.953984,37.535420
...,...,...,...,...,...,...,...,...
37452,106900002,중랑02,22,106900028,7511,서일대정문,127.095896,37.587753
37453,106900002,중랑02,23,106900025,7526,새마을금고,127.097335,37.589118
37454,106900002,중랑02,24,106900002,7527,공판장,127.099060,37.588522
37455,106900002,중랑02,25,106900026,7528,진주빌라.바다약국,127.100669,37.587783
37456,106900002,중랑02,26,106900023,7529,진로아파트앞.종점,127.101491,37.587650

In [15]:
way=data[data['노선명']=='0017']
# way['정류소명']

In [18]:
y=data.pivot_table(index=['정류소명','노선명'])
y

                  ARS-ID      NODE_ID         X좌표        Y좌표       노선ID    순번
정류소명     노선명
(구)동양마트앞 광진01     5555.0  104900102.0  127.090017  37.541551  104900005  13.0
(구)법화사   성북02     8649.0  107900089.5  127.011033  37.584589  107900003  19.5
10단지     441     37003.0  220000007.0  126.996577  37.435264  100100070  85.0
         502     37003.0  220000007.0  126.996577  37.435264  100100410  92.0
         540     37003.0  220000007.0  126.996577  37.435264  100100083  62.0
...                  ...          ...         ...        ...        ...   ...
힐탑       8003     1586.0  100900079.0  126.969041  37.611640  107000004  11.0
힐튼호텔     04       2285.0  101000265.0  126.976612  37.556606  106000002   4.0
         402      2284.5  101000265.5  126.976633  37.556405  100100063  56.5
         405      2284.5  101000265.5  126.976633  37.556405  100100597  45.0
         TOUR02   3906.0  101000327.0  126.977274  37.554832  101000001   5.0

[26566 rows x 6 columns]